type/epic:
  - head-branch: ^epic/
type/feature:
  - head-branch: ^feature/
type/bug:
  - head-branch: ^bug/
type/housekeeping:
  - head-branch: ^housekeeping/
type/dependencies:
  - head-branch: ^dependabot/

'module/retrofit-core':
  - any:
      - src/Core/**/*
'module/retrofit-client-guzzle7':
  - any:
      - src/Client/Guzzle7/**/*
