type/epic:
  - head-branch: ^epic/
type/feature:
  - head-branch: ^feature/
type/bug:
  - head-branch: ^bug/
type/housekeeping:
  - head-branch: ^housekeeping/
type/dependencies:
  - head-branch: ^dependabot/

module/retrofit-core:
  - src/Core/**/*
module/retrofit-client-guzzle7:
  - src/Client/Guzzle7/**/*
