type/epic:
  - head-branch: ^type/epic
type/feature:
  - head-branch: ^type/feature
type/bug:
  - head-branch: ^type/bug
type/housekeeping:
  - head-branch: ^type/housekeeping
type/dependencies:
  - head-branch: ^type/dependabot
