name: Add labels

on:
  pull_request:
    branches:
      - '*'

jobs:
  type-label:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Triage labels
        uses: actions/labeler@v5
