name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ 8.2 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.3
        with:
          fetch-depth: 0

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
        env:
          fail-fast: true

      - name: Install Composer dependencies
        run: composer install --no-progress

      - name: Run tests
        run: ./vendor/bin/phpunit --configuration ./phpunit.xml.dist

