name: PHP-CS-Fixer

on:
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ 8.2 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5
        with:
          fetch-depth: 0

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
        env:
          fail-fast: true

      - name: Install PHP-CS-Fixer
        run: composer --working-dir=vendor-bin/php-cs-fixer --no-progress install

      - name: Run PHP-CS-Fixer
        run: ./vendor-bin/php-cs-fixer/vendor/bin/php-cs-fixer fix

      - name: Commit lint changes
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: Apply PHP-CS-Fixer changes
