name: Publish Sub-Split

on:
  push:
    branches:
      - main
  create:
    tags:
      - '*'
  delete:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Generate RetrofitBot token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          app-id: ${{ secrets.RETROFIT_BOT_APP_ID }}
          private-key: ${{ secrets.RETROFIT_BOT_PRIVATE_KEY }}
          owner: retrofit-php
          repositories: |
            retrofit-php
            retrofit-php-core
            retrofit-php-client-guzzle7
            retrofit-php-converter-symfony-serializer

      - name: Set RetrofitBot token
        uses: frankdejonge/use-github-token@15e6289d07c12b3b1603268a628bb74f2e9765f4 # 1.1.0
        with:
          authentication: 'RetrofitBot:${{ steps.app-token.outputs.token }}'
          name: github-actions[bot]
          email: github-actions[bot]@users.noreply.github.com

      - name: Configure git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Cache splitsh-lite
        id: splitsh-cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ./.splitsh
          key: ${{ runner.os }}-splitsh-d-101

      - name: Publish using splitish
        uses: frankdejonge/use-subsplit-publish@0001015147267203898034927e8cccad3a7a9aa7 # @1.1.0
        with:
          source-branch: main
          config-path: ./config.subsplit-publish.json
          splitsh-path: ./.splitsh/splitsh-lite
          splitsh-version: v1.0.1
