name: Publish Sub-Split

on:
  push:
    branches:
      - main
  create:
    tags:
      - '*'
  delete:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Generate RetrofitBot token
        id: generate_token
        uses: tibdex/github-app-token@v1.8.0
        with:
          app_id: ${{ secrets.RETROFIT_BOT_APP_ID }}
          private_key: ${{ secrets.RETROFIT_BOT_PRIVATE_KEY }}

      - name: Set RetrofitBot token
        uses: frankdejonge/use-github-token@1.0.2
        with:
          authentication: 'RetrofitBot:${{ steps.generate_token.outputs.token }}'
          name: github-actions[bot]
          email: github-actions[bot]@users.noreply.github.com

      - name: Cache splitsh-lite
        id: splitsh-cache
        uses: actions/cache@v3.3.1
        with:
          path: ./.splitsh
          key: ${{ runner.os }}-splitsh-d-101

      - name: Publish using splitish
        uses: frankdejonge/use-subsplit-publish@1.0.0-beta.7
        with:
          source-branch: main
          config-path: ./config.subsplit-publish.json
          splitsh-path: ./.splitsh/splitsh-lite
          splitsh-version: v1.0.1
