name: Static analysis

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  phpstan:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ 8.2 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
        env:
          fail-fast: true

      - name: Install Composer dependencies
        run: composer install --no-progress

      - name: Install PHPStan
        run: composer --working-dir=vendor-bin/phpstan --no-progress install

      - name: Run PHPStan
        run: ./vendor-bin/phpstan/vendor/bin/phpstan --configuration=./phpstan.neon.dist --autoload-file=./vendor/autoload.php analyse
